# Source-tree types for the private Cython extension (never a runtime fallback).

from collections.abc import Iterable

from ztm_frontend.journey import Network, _Label, _Profile

class PreparedNet:
    def __init__(self, net: Network) -> None: ...
    def payload_bytes(self) -> int: ...
    def late(self, board: int, alight: int) -> int: ...

class PreparedQuery:
    def __init__(self, network: PreparedNet, to_target: list[float], permission_words: int) -> None: ...
    @property
    def network(self) -> PreparedNet: ...
    def peak_permission_words(self) -> int: ...

class NativeState:
    def __init__(self, query: PreparedQuery, profile: _Profile) -> None: ...
    @property
    def query(self) -> PreparedQuery: ...
    def run(self, profile: _Profile, after: int, boarding: Iterable[int] | None = None) -> list[_Label]: ...
    def stats(self) -> dict[str, int]: ...
